# Generated by Django 2.2.1 on 2019-11-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_year_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hydrate_Production', models.IntegerField()),
                ('Specific_Consumption', models.IntegerField()),
                ('No_of_days', models.IntegerField()),
                ('Consumption', models.IntegerField()),
                ('Daily_Consumption', models.IntegerField()),
            ],
        ),
    ]
