# Generated by Django 2.2.1 on 2019-12-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_year_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bauxite_Plan', models.CharField(max_length=100)),
                ('Apr', models.IntegerField()),
                ('May', models.IntegerField()),
                ('Jun', models.IntegerField()),
                ('Jul', models.IntegerField()),
                ('Aug', models.IntegerField()),
                ('Sep', models.IntegerField()),
                ('Oct', models.IntegerField()),
                ('Nov', models.IntegerField()),
                ('Dec', models.IntegerField()),
                ('Jan', models.IntegerField()),
                ('Feb', models.IntegerField()),
                ('Mar', models.IntegerField()),
            ],
        ),
    ]
