# Generated by Django 2.2.1 on 2019-12-02 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_year_data',
            old_name='Bauxite_Plan',
            new_name='BauxitePlan',
        ),
    ]
