# Generated by Django 2.2.1 on 2019-12-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191202_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_year_data',
            name='Apr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='main_year_data',
            name='Aug',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='main_year_data',
            name='Dec',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='main_year_data',
            name='Feb',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='main_year_data',
            name='Jan',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='main_year_data',
            name='Jul',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='main_year_data',
            name='Jun',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='main_year_data',
            name='Mar',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='main_year_data',
            name='May',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='main_year_data',
            name='Nov',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='main_year_data',
            name='Oct',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='main_year_data',
            name='Sep',
            field=models.IntegerField(null=True),
        ),
    ]
