from django.db import models

# Create your models here.

# Create your models here.
class main_year_data(models.Model):
	 BauxitePlan = models.CharField(max_length = 100)
	 Apr = models.IntegerField(null = True,blank = True)
	 May = models.IntegerField(null = True,blank = True)
	 Jun = models.IntegerField(null = True,blank = True)
	 Jul = models.IntegerField(null = True,blank = True)
	 Aug = models.IntegerField(null = True,blank = True)
	 Sep = models.IntegerField(null = True,blank = True)
	 Oct = models.IntegerField(null = True,blank = True)
	 Nov = models.IntegerField(null = True,blank = True)
	 Dec = models.IntegerField(null = True,blank = True)
	 Jan = models.IntegerField(null = True,blank = True)
	 Feb = models.IntegerField(null = True,blank = True)
	 Mar = models.IntegerField(null = True,blank = True)

	 # Hydrate_Production = models.IntegerField()
	 # Specific_Consumption = models.IntegerField()
	 # No_of_days = models.IntegerField()
	 # Consumption = models.IntegerField()
	 # Daily_Consumption = models.IntegerField()
	 # Opening_Stock = models.IntegerField()
	 # At_Plant = models.IntegerField()
	 # At_Port  = models.IntegerField()
	 # On_Sea = models.IntegerField()
	 # Receipt_at_Plant = models.IntegerField()
	 # Andru = models.IntegerField()
	 # Balco	 = models.IntegerField()
	 # OMC = models.IntegerField()
	 # Import	= models.IntegerField()
	 # Rake_Receipt_at = models.IntegerField()
	 # Andru_1= models.IntegerField()
	 # Balco_1	= models.IntegerField()
	 # omc_capative = models.IntegerField()
	 # Import_capative = models.IntegerField()
	 # Avg_No_or_rake = models.IntegerField()
	 # Receipt_at_Destination_Port = models.IntegerField()
	 # MRNAlcoa = models.IntegerField()
	 # CBGRTA1 = models.IntegerField()
	 # CBGRTA2 = models.IntegerField()
	 # GACEGA = models.IntegerField()
	 # MRNTricon = models.IntegerField()
	 # To_be_procured = models.IntegerField()
	 # Loading_at_Origin_Port = models.IntegerField()
	 # MRNAlcoa = models.IntegerField()
	 # CBGRTA_1 = models.IntegerField()
	 # CBGRTA2  = models.IntegerField()
	 # GACEGA = models.IntegerField()
	 # MRNTricon = models.IntegerField()
	 # Closing_Stock	= models.IntegerField()
	 # At_Plant_1 = models.IntegerField()
	 # At_Port_1 = models.IntegerField()
	 # On_Sea_2 = models.IntegerField()
	 # At_Plant_2 = models.IntegerField()
	 # At = models.IntegerField()
	 # PortRITSidings = models.IntegerField()
	 # On_Sea_1 = models.IntegerField()
	 # Total_System = models.IntegerField()				